# This script takes in the raw outputs generated by new-lms_read.R
# and the raw littermates file generated by ablat_read.R, combines them
# and performs a series of transformations in the data, namely
# * correcting for fluorescence decay along the Z-axis
# * transforms fluorescence values of NANOG and GATA6 obtained with 
#   multiple antibodies onto an equivalent relative scale

# Check if setup.R has been ran
setup.ran <- exists('looks')
if (setup.ran == F) { 
  source('./src/setup.R')
}
rm(setup.ran)

# Check if data is already loaded 
data.exsts <- exists('new.lms')
if(data.exsts == F) { 
  new.lms <- read.csv('./data/raw/new-lms-raw.csv')
  new.lms.ref <- rbind(read.csv('./references/new-littermates_exp_ref.csv'), 
                       read.csv('./references/fgf4-lms_exp_ref.csv'))
}
rm(data.exsts)

# Load functions that will be used in the script
source('./src/eb_cor.R')

# Remove wt embryos used for antibody test, negative controls
# and embryos of unknown genotype
new.lms <- subset(new.lms, Treatment == 'Littermate' & 
                    Genotype1 != 'unknown')

# Load immunofluorescence reference files
new.lms.if <- read.csv('./references/new-littermates_if.csv')
f4.lms.if <- read.csv('./references/fgf4-lms_if.csv')

# Extract info for Channels 2 and their associated marker (primary ab) 
# and secondary antibody (ab.2)
newlms.ch2 <- new.lms.if %>% 
  filter(Channel == 'CH2') %>%
  group_by(Experiment, Litter, Genotype1, Channel, Marker) %>%
  summarize()
f4.lms.ch2 <- f4.lms.if %>% 
  filter(Channel == 'CH2') %>%
  group_by(Experiment, Litter, Channel, Marker) %>%
  summarize()

## Cast both to wide format
newlms.ch2 <- dcast(newlms.ch2, Experiment + Genotype1 ~ Channel, 
                    value.var = 'Marker')
newlms.ch2 <- rename(newlms.ch2, CH2.marker = CH2)

f4.lms.ch2 <- dcast(f4.lms.ch2, Experiment ~ Channel, value.var = 'Marker')
f4.lms.ch2 <- rename(f4.lms.ch2, CH2.marker = CH2)

# Split new.lms into Fgf4 subet and rest, to incorporate IF information
# without losing data, as Fgf4 if file doesn't account for Genotype
aa <- subset(new.lms, Gene1 != 'Fgf4')
bb <- subset(new.lms, Gene1 == 'Fgf4')

# Incorporate IF data into main tables
aa <- merge(aa, new.lms.if)
aa <- merge(aa, newlms.ch2)
bb <- merge(bb, f4.lms.if)
bb <- merge(bb, f4.lms.ch2)

# Bind again aa and bb into new.lms and clean up
new.lms <- rbind.fill(aa, bb)
rm(newlms.ch2, f4.lms.ch2, aa, bb)

## Merge IF tables, as they will be used later
new.lms.if <- merge(new.lms.if, f4.lms.if)

# Modify Experiment variable to account for different genotypes
new.lms$Experiment <- paste(new.lms$Experiment, new.lms$Genotype1, sep = '.')
new.lms.if$Experiment <- paste(new.lms.if$Experiment, 
                               new.lms.if$Genotype1, sep = '.')

################################################################################
## Correct Z-associated fluorescence decay
################################################################################

# Since eb.cor() is designed to correct one channel (variable) at a time
# we need to loop it through the fluorescence channels we want to correct

# Define the possible channels to go through
channels <- c('CH1.Avg', 'CH2.Avg', 'CH3.Avg', 'CH5.Avg')

# Create an empty matrix to hold the corrected values
# with the length of the number of cells in the dataset
ebLogCor <- matrix(0, nrow = length(new.lms$Embryo_ID), 
                   # and as many columns as channels
                   ncol = length(channels),
                   dimnames = list(c(), channels))

# For each channel in 'channels', perform Empirical Bayes correction 
# and store in the corresponding column in 'ebLogCor'
# Critically, use the marker for CH2 as grouping variable for ebcor()
# (see annotation in eb_cor.R for details)
for (c in channels) {
  ebLogCor[, c] <- ebcor(new.lms, c, group = new.lms$CH2.marker)
}
# Convert ebLogCor to data frame and rename columns to CHX.ebLogCor
ebLogCor <- data.frame(ebLogCor)
ebLogCor <- rename(ebLogCor, CH1.ebLogCor = CH1.Avg, 
                   CH2.ebLogCor = CH2.Avg, 
                   CH3.ebLogCor = CH3.Avg,
                   CH5.ebLogCor = CH5.Avg)

# Incorporate ebLogCor values into main table
new.lms <- cbind(new.lms, ebLogCor)
rm(ebLogCor)

################################################################################
## Incorporate littermate data from ablations experiments
################################################################################

# ## Read in all littermates from the ablation dataset
# ## In these, values have been corrected for fluorescence decay on Z
# ## but are otherwise untransformed and have no identity assigned
# ablat.lms <- read.csv('./data/interim/lms-ablation-raw.csv')
# 
# # Rename the variable group.median to litter.median
# ablat.lms <- rename(ablat.lms, litter.median = group.median)
# 
# # Select variables on each data set that are contained in the other
# # WARNING: I have verified this step doesn't drop any critical variable 
# # in these dataset, do not apply directly to other data without checking first
# ablat.lms <- ablat.lms[colnames(ablat.lms)[
#   which(colnames(ablat.lms) %in% colnames(new.lms))]]
# new.lms <- new.lms[colnames(new.lms)[
#   which(colnames(new.lms) %in% colnames(ablat.lms))]]
# 
# # Combine both datasets
# new.lms <- rbind(new.lms, ablat.lms)
# new.lms <- stage(new.lms)

################################################################################
## Order factors
################################################################################

new.lms$TE_ICM <- factor(new.lms$TE_ICM, levels = c('TE', 'ICM'))
new.lms$Genotype1 <- factor(new.lms$Genotype1, 
                            levels = c('wt', 'wt/fl', 'het', 'fl/ko', 
                                       'ko', 'tbd'))


