# This file reads in curated files for the ablation dataset
# from the corresponding folder (data/corfiles)
# combines them into one table and cleans up the data

# Check that setup.R has been ran
setup.ran <- exists('looks')
if (setup.ran == F) { 
  source('./src/setup.R')
}
rm(setup.ran)

# Load functions that will be used in the script
source('./src/functions/do_counts.R')
source('./src/functions/stage.R')

# Define the location of live images taken at time of ablation
my.dir <- './data/corfiles/ablat-t0_corf/'

# Read in each of the files in the ablat-t0 folder and combine in one data frame
my.files <- dir(my.dir)
ablat.t0 <- do.call(rbind.fill, 
                   lapply(my.files, 
                          function(x) read.csv(paste(my.dir, x, sep = ''))))

# Log the embryos loaded
n.start.t0 <- unique(ablat.t0$Embryo_ID)

# Remove spurious column generated by MS Excel
ablat.t0$X.1 <- NULL
# Add a timepoint variable ('t0' for all) and 
# create a TE_ICM variable from Identity variable
ablat.t0$timepoint <- 't0'
ablat.t0$TE_ICM <- ifelse(ablat.t0$Identity %in% c('EPI', 'PRE', 'DP'), 'ICM', 
                          ifelse(is.na(ablat.t0$Identity), 'unknown', 'TE'))

# Order identity levels
ablat.t0$Identity <- factor(ablat.t0$Identity, 
                            levels = c('PRE', 'DP', 'EPI', 'TE', 'unknown'))

# Define the location of images of fixed embryos, the end of the experiment
my.dir <- './data/corfiles/ablat-fix_corf/'

# Read in each of the files in the ablat-fix folder and combine in one data frame
my.files <- dir(my.dir)
ablat <- do.call(rbind.fill, 
                 lapply(my.files, 
                        function(x) read.csv(paste(my.dir, x, sep = ''))))

# Remove spurious Excel columns
ablat[c('X.1', 'X.2')] <- NULL

# Record the number of fixed embryos loaded
n.start <- unique(ablat$Embryo_ID)

# Read in experimental metadata reference file
ablat.ref <- read.csv('./references/ablat_exp_ref.csv')
# Drop maually-generated 'Treatement stage' column (will be created later)
ablat.ref$Tt_stage <- NULL

# Combine referene data with each data table
ablat <- merge(ablat, ablat.ref)
ablat.t0 <- merge(ablat.t0, ablat.ref)

# Calculate total cell count, ICM cell count and group median with do_counts
ablat <- do.counts(ablat, sep.treatment = T)

# In reference Littermates ('Littermates'), which were fixed at their t0, 
# assign the total cell count (Cellcount) as the t0 cell count (Cellcount_t0)
# since they coincide
ablat$Cellcount_t0[which(ablat$Treatment == 'Littermate')] <- 
  ablat$Cellcount[which(ablat$Treatment == 'Littermate')]

# Convert target to 'none' for Controls and Littermates (all untargeted)
ablat$target[which(ablat$Treatment %in% c('Control', 'Littermate'))] <- 'none'

# Drop 'Test' embryos, which were used to test ablation conditions
ablat <- subset(ablat, Treatment != 'Test')
# Drop embryos that have less than 60 cells (the lower end of control range) 
# at the end of the experiment or embryos which look sick by visual inspecton
lil <- unique(subset(ablat, Treatment == 'Ablated' & Cellcount < 60)$Embryo_ID)
goners <- c(lil, '013018Abl_CK2')
ablat <- subset(ablat, !Embryo_ID %in% goners)

################################################################################
# Determine the stage of embryos at beginning of experiment (time of ablation)
# in the main data frame containing fixed, end point data (ablat)
################################################################################

# For embryos where there is information from live images of the Cellcount at t0
# (Cellcount_t0 != NA) use it to determine the initial stage (Stage.t0).

# For embryos where there is no data on initial Cellcount for each embryo 
# (no nuclear mKate2 or embryos not imaged through at start), use the median
# cell count of the corresponding reference littermates as an estimator.

# Since Cellcount for Littermate is Cellcount_t0, both cases can be calculated
# at once. First, extract embryos where Cellcount_t0 exists
ablat.a <- ablat %>% filter(is.na(Cellcount_t0) == F)
# Then use dplyr to calculate the median each litter in that subset of data
tt.stage <- ablat.a %>% group_by(Litter) %>% 
  summarize(litter.median_t0 = median(Cellcount_t0))
# Bin values in 20-cell bins and store as Stage.t0
cuts <- seq(30, 210, by = 20)
tt.stage$Stage.t0 <- cut(tt.stage$litter.median_t0, 
                         breaks = cuts, right = F, include.lowest = T)
# Extract the combination of Litter and Stage.t0 and combine with main dataframe
tt.stage <- tt.stage %>% select(Litter, Stage.t0)
ablat <- merge(ablat, tt.stage)
rm(tt.stage, ablat.a)

# Extract Stage.t0 information and write it out to ./data/interim
tt.stage <- ablat %>% group_by(Litter, Stage.t0) %>% summarize()
write.csv(tt.stage, file = './references//ablat_t0-stage.csv', row.names = F)
rm(tt.stage)

################################################################################
# Determine Stage.t0 for live data (ablat.t0)
################################################################################

# Subset non-littermates from live data (Controls and Ablated)
# for which I have cell counts of the whole embryo
ablat.t0.new <- subset(ablat.t0, Treatment != 'Littermate' & 
                         is.na(Cellcount_t0) == F)

# Extract Stage.t0 and Embryo_ID for all endpoint littermates data
lms.stage <- ablat %>% filter(Treatment == 'Littermate') %>% 
  select(Litter, Stage.t0) %>% 
  group_by(Litter, Stage.t0) %>% summarize()

# Add to embryos that are not in ablat.t0.new (no cell or lineage counts at t0) 
# the corresponding Stage.t0 variable from their fixed littermates (lms.stage)
aa <- subset(ablat.t0, !Embryo_ID %in% unique(ablat.t0.new$Embryo_ID))
lms.stage <- as.data.frame(subset(lms.stage, Litter %in% unique(aa$Litter)))
aa <- merge(aa, lms.stage)
rm(lms.stage)

# Stage embryos that are in ablat.t0.new (with live total and ICM cell counts)
# based on their total cell count at t0
tt.stage <- ablat.t0.new %>% 
  group_by(Embryo_ID, Cellcount_t0) %>% 
  summarize()
tt.stage$Stage.t0 <- cut(tt.stage$Cellcount_t0, 
                         breaks = cuts, right = F, include.lowest = T)
tt.stage <- tt.stage %>% select(Embryo_ID, Stage.t0)
ablat.t0.new <- merge(ablat.t0.new, tt.stage)
rm(tt.stage, cuts)

# Re create ablat.t0 (now with Stage.t0) by combining aa and ablat.t0.new
ablat.t0 <- rbind(aa, ablat.t0.new)
rm(aa, ablat.t0.new)

# Calculate the median cell count for each litter at t=0, 
# as a metric to stage them without bins.
yea <- ablat %>% filter(is.na(Cellcount_t0) == F) %>% 
  group_by(Litter) %>% 
  summarize(litter.median.t0 = median(Cellcount_t0))
ablat <- merge(ablat, yea)
rm(yea)

################################################################################
# Write files out to disk for later use
################################################################################

# Write out fixed and live data tables as raw data (untransformed)
write.csv(ablat, file = './data/raw/ablat-fixed-raw.csv', row.names = F)
write.csv(ablat.t0, file = './data/raw/ablat-t0-raw.csv', row.names = F)
