# This script takes in the raw output generated by compounds_read.R
# and performs a series of transformations in the data, namely
# * correcting for fluorescence decay along the Z-axis
# * transforms fluorescence values of NANOG and GATA6 obtained with 
#   multiple antibodies onto an equivalent relative scale

# Check if setup.R has been ran
setup.ran <- exists('looks')
if (setup.ran == F) { 
  source('./src/setup.R')
}
rm(setup.ran)

# Check if data is already loaded 
data.exsts <- exists('compos')
if(data.exsts == F) { 
  compos <- read.csv('./data/raw/compounds-raw.csv')
  compos.ref <- rbind(read.csv('./references/compounds_exp_ref.csv'))
}
rm(data.exsts)

# If raw data doesn't exist, run script to generate it
data.exsts <- exists('compos')
if(data.exsts == F) { 
  source('./src/data/compounds_read.R')
  compos.ref <- rbind(read.csv('./references/compounds_exp_ref.csv'))
}
rm(data.exsts)

# Source functions that will be used in the script
source('./src/functions/eb_cor.R')
source('./src/functions/tx_channels.R')

# Load immunofluorescence reference file and merge with main table
compos.if <- read.csv('./references/compounds_if.csv')
compos <- merge(compos, compos.if)

# Order genotypes
compos$Genotype1 <- factor(compos$Genotype1, levels = c('wt', 'het', 'ko', 
                                                        'mosaic', 'unknown', 
                                                        'tbd'))
compos$Genotype2 <- factor(compos$Genotype2, levels = c('wt', 'het', 'ko', 
                                                        'mosaic', 'unknown', 
                                                        'tbd'))

# Extract marker info for each experiment
unicos <- compos %>% filter(Channel %in% c('CH2', 'CH3', 'CH5')) %>% 
  group_by(Experiment, Channel, Marker) %>% 
  summarize()
unicos <- dcast(unicos, Experiment ~ 
                  Channel, value.var = 'Marker')

# Write out unicos table to disk
write.csv(unicos, file = './references/compounds_unicos.csv')

# Pluck out only Channel 2 information, necessary to group embryos
# for fluorescence correction below
compos.ch2 <- unicos %>% select(Experiment, CH2)
compos.ch2 <- rename(compos.ch2, CH2.marker = CH2)
compos <- merge(compos, compos.ch2)
rm(compos.ch2)

################################################################################
# Write out a table with N numbers for each Gene and Genotype
################################################################################

n.embryos <- compos %>%  
  group_by(Embryo_ID, Gene1, Genotype1, 
           Gene2, Genotype2) %>% 
  summarize() %>% 
  group_by(Gene1, Genotype1, 
           Gene2, Genotype2) %>% 
  summarize(N = n())

# Write N numbers out to disk
write.csv(n.embryos, file = './results/compounds_N-embryos.csv', row.names = F)

################################################################################
# Correct for fluorescence decay along the Z-axis
################################################################################

# Since eb.cor() is designed to correct one channel (variable) at a time
# we need to loop it through the fluorescence channels we want to correct

# Define the possible channels to go through
channels <- c('CH1.Avg', 'CH2.Avg', 'CH3.Avg', 'CH5.Avg')

# Create an empty matrix to hold the corrected values
# with the length of the number of cells in the dataset
ebLogCor <- matrix(0, nrow = length(compos$Embryo_ID), 
                   # and as many columns as channels
                   ncol = length(channels),
                   dimnames = list(c(), channels))

# For each channel in 'channels', perform Empirical Bayes correction 
# and store in the corresponding column in 'ebLogCor'
# Critically, use the marker for CH2 as grouping variable for ebcor()
# (see annotation in eb_cor.R for details)
for (c in channels) {
  ebLogCor[, c] <- ebcor(compos, c, group = compos$CH2.marker)
}
# Convert ebLogCor to data frame and rename columns to CHX.ebLogCor
ebLogCor <- data.frame(ebLogCor)
ebLogCor <- rename(ebLogCor, CH1.ebLogCor = CH1.Avg, 
                   CH2.ebLogCor = CH2.Avg, 
                   CH3.ebLogCor = CH3.Avg,
                   CH5.ebLogCor = CH5.Avg)

# Incorporate ebLogCor values into main table
compos <- cbind(compos, ebLogCor)
rm(ebLogCor)

################################################################################
# Transform fluorescence values obtained with NANOG.rat and GATA6.rb to
# NANOG.rb and GATA6.gt equivalents and re-scale to 0-1
################################################################################

# Create a vector with unique combinations of antibodies and stainings
# and a list with the corresponding experiments stained that way
stains <- unique(paste(unicos$CH2, unicos$CH3, unicos$CH5))
exps <- list()
for(s in 1:length(stains)) { 
  exps[[s]] <- unique(unicos$Experiment[which(paste(unicos$CH2, 
                                                    unicos$CH3, 
                                                    unicos$CH5) == stains[s])])
}

# Use tx.channel function to transform NANOG(rat) into NANOG(rb)-equivalents
compos <- tx.channel(compos, what.subset = exps[[1]], what.model = ng.model, 
                      input.ch = 'CH2', end.ch = 'CH3')

# Re-scale fluorescence values to 0-1 scale

# Create vectors of names for the original and transformed fluorescence values
pre.cols <- colnames(compos)[grep('ebLogCor$', colnames(compos))]
post.cols <- paste(pre.cols, 's', sep = '.')
mo.cols <- colnames(compos)[grep('ebLogCor.x', colnames(compos))]
pre.cols <- c(pre.cols, mo.cols)
post.cols <- c(post.cols, paste(mo.cols, 's', sep = ''))
rm(mo.cols)

# Create an empty matrix to hold the re-scaled values (.s) for each channel
s.cols <- matrix(0, nrow = length(compos$CH1.ebLogCor), 
                 ncol = length(post.cols), 
                 dimnames = list(c(), post.cols))
s.cols <- data.frame(s.cols)
# and incorporate into main data frame
compos <- cbind(compos, s.cols)
rm(s.cols)

# Cycle through the list of experiments and make the values of each channel 
# relative to the maxima in that group - thus maintaining the relative levels
# between embryos of different litters & stages while eliminating differences
# due to antibody combinations (which are only technical)
for(e in 1:length(exps)) { 
  # Split data in a subset with relevant experiments and another without
  sile <- subset(compos, Experiment %in% exps[[e]])
  nole <- subset(compos, !Experiment %in% exps[[e]])
  # Rescale each channel given in pre.cols to the maxima of that channel
  # in the given group (sile) and store the re-scaled value in the
  # corresponding transformed vairable (its cognate in post.col)
  for(c in 1:length(pre.cols)) {
    sile[post.cols[c]] <- sile[pre.cols[c]] / max(sile[pre.cols[c]])
  }
  # Combine both datasets again before next loop
  compos <<- rbind(sile, nole)
}
rm(sile, nole)

################################################################################
# Write files out to disk for later use
################################################################################

write.csv(compos, file = './data/interim/compounds-tx.csv', row.names = F)


##