# This script takes in the raw output generated by emb-xim_read.R
# and performs transformations on the data, namely:
# * correcting for fluorescence decay along the Z-axis

# Check that setup.R has been ran
setup.ran <- exists('looks')
if (setup.ran == F) { 
  source('./src/setup.R')
}
rm(setup.ran)

# Check if data is already loaded and read it in if not
data.exsts <- exists('g6.chimeras')
if(data.exsts == F) { 
  g6.chimeras <- read.csv('./data/raw/emb-xim-raw.csv')
  g6.ref <- read.csv('./references/emb-xim_exp_ref.csv')
}
rm(data.exsts)

# If there is no raw data, run script to generate it
data.exsts <- exists('g6.chimeras')
if(data.exsts == F) { 
  source('./src/data/emb-xim_read.R')
  g6.ref <- read.csv('./references/emb-xim_exp_ref.csv')
}
rm(data.exsts)

# Load functions that will be used in the script
source('./src/functions/eb_cor.R')

# Load immunofluorescence reference file and merge with main table
g6.if <- read.csv('./references/emb-xim_if.csv')
g6.chimeras <- merge(g6.chimeras, g6.if)

# Extract info for Channel 2 and its associated secondary antibody (ab.2)
g6.ch2 <- subset(g6.if, Channel == 'CH2') %>% 
  group_by(Experiment, Treatment, Marker, ab.2) %>%
  summarize()
g6.ch2 <- rename(g6.ch2, CH2.marker = Marker, CH2.ab2 = ab.2)

# Incorporate Channel 2 info into main table
g6.chimeras <- merge(g6.chimeras, g6.ch2)
rm(g6.ch2)

################################################################################
# Correct for fluorescence decay along the Z-axis
################################################################################

# Use the function ebcor() for channels 1 (Hoechst), 3 (NANOG) and 5 (GATA6)
# GFP will be corrected differently - see below

# Define the possible channels to go through
channels <- c('CH1.Avg', 'CH3.Avg', 'CH5.Avg')
# Create an empty matrix to hold the corrected values
# with the length of the number of cells in the dataset
ebLogCor <- matrix(0, nrow = length(g6.chimeras$Embryo_ID), 
                   # and as many columns as channels
                   ncol = length(channels),
                   dimnames = list(c(), channels))
# For each channel in 'channels', perform EB correction 
# and store in the corresponding column in 'ebLogCor'
# Critically, use the secondary antibody as grouping variable for ebcor()
# (see annotation in eb_cor.R for details)
for (c in channels) {
  ebLogCor[, c] <- ebcor(g6.chimeras, c, 
                         group = g6.chimeras$CH2.ab2)
}
# Convert ebLogCor to data frame and rename columns to CHX.ebLogCor
ebLogCor <- data.frame(ebLogCor)
ebLogCor <- rename(ebLogCor, CH1.ebLogCor = CH1.Avg, 
                   CH3.ebLogCor = CH3.Avg,
                   CH5.ebLogCor = CH5.Avg)

## Combine chimeras with the EB corrected values
g6.chimeras <- cbind(g6.chimeras, ebLogCor)
rm(ebLogCor)

# Correct GFP channel for Z-associated fluorescence decay
# The ebcor() function performs poorly on this channel because of the mix
# of GFP+ and GFP- cells in the embryos, which results in large over-
# and udercorrection that affects the downstream automatic classification.

# Instead of using ebcor() for all cells, I split the dataset:
# * embryos where Channel 2 corresponds to CDX2, to which I apply ebcor() 
# * embryos where Channel 2 is anti-GFP staining, where I correct the Z-decay 
#   using the slope of a linear regression model [log(CH2.Avg) ~ Z] 
#   calculated for all of the cells stained for GFP

# Split the dataset
cc <- subset(g6.chimeras, CH2.ab2 == 'af488.m')
gg <- subset(g6.chimeras, CH2.ab2 == 'af488.ck')

# Apply ebcor() to CDX2 subset
cc$CH2.logCor <- ebcor(cc, 2)

# Apply linear correction to GFP subset
gg.slope <- summary(lm(log(CH2.Avg + 0.0001) ~ Z, 
                       data = gg))$coefficients[2, 1]
gg$CH2.logCor <- log(gg$CH2.Avg) - gg.slope * gg$Z
rm(gg.slope)

# Combine both subsets again
g6.chimeras <- rbind(cc, gg)
rm(cc, gg)

################################################################################
# Write data out to interim folder
write.csv(g6.chimeras, file = './data/interim/emb-xim-tx.csv', row.names = F)

