# This script counts cells of each type in the embryo-embryo chimeras dataset
# generated by emb-xim_classify.R
# Note I am using the ICM cell identity determined by Hierarchical clustering

# Check if setup.R has been ran
setup.ran <- exists('looks')
if (setup.ran == F) { 
  source('./src/setup.R')
}
rm(setup.ran)

# Check if data is already loaded and read it in if not
data.exsts <- exists('g6.chimeras')
if(data.exsts == F) { 
  g6.chimeras <- read.csv('./data/processed/emb-xim-processed.csv')
  g6.ref <- read.csv('./references/emb-xim_exp_ref.csv')
}
rm(data.exsts)

# If there is no processed data, run script to generate it
data.exsts <- exists('g6.chimeras')
if(data.exsts == F) { 
  source('./src/data/emb-xim_classify.R')
  g6.ref <- read.csv('./references/emb-xim_exp_ref.csv')
}
rm(data.exsts)

################################################################################
# Calculate the number of embryos per experimental group
# (genotype x % donor x embryo size combination) and write it out to disk
################################################################################

n.embryos <- g6.chimeras %>% 
  filter(Channel == 'CH2') %>% 
  group_by(Embryo_ID, 
           H_genotype, 
           Embryo_size, 
           t0.donor) %>% 
  summarize() %>% 
  group_by(H_genotype, 
           Embryo_size, 
           t0.donor) %>% 
  summarize(N.embryos = n())
n.embryos <- dcast(n.embryos, Embryo_size + H_genotype ~ t0.donor, 
                   value.var = 'N.embryos')
write.csv(n.embryos, file = './results/emb-xim_N-embryos.csv', 
          row.names = FALSE)

################################################################################
# Count the number of host (GFP- or control) 
# and donor (GFP+) cells in each embryo
################################################################################
g6.typecount <- g6.chimeras %>% 
  filter(Channel == 'CH2') %>% 
  group_by(Embryo_ID, Litter, Experiment, 
           Treatment, Embryo_size, 
           Cellcount, icm.count, 
           H_genotype, D_genotype, 
           t0.donor, cell_type) %>%
  summarise(type.count = n())

# Account for zeroes - for instance, the number of donor cells in 
# control embryos, which is zero (they are all classified as host).
# Cast to wide format
m.g6 <- dcast(g6.typecount, Embryo_ID + Litter + Experiment + Treatment + 
                Embryo_size + Cellcount + icm.count + 
                H_genotype + D_genotype + 
                t0.donor ~ cell_type, 
              value.var = 'type.count')
# Replace NAs with zeros in donor and host columns
m.g6$donor[is.na(m.g6$donor)] <- 0
m.g6$host[is.na(m.g6$host)] <- 0
# Melt table back to long format
g6.typecount <- melt(m.g6, id.vars = c('Embryo_ID', 'Litter', 
                                       'Experiment', 'Treatment', 
                                       'Embryo_size', 'Cellcount', 
                                       'icm.count', 'H_genotype', 
                                       'D_genotype', 't0.donor'), 
                     variable.name = 'cell_type', value.name = 'type.count')
rm(m.g6)
# And the percentage of the total they represent
g6.typecount$pc.type <- g6.typecount$type.count/g6.typecount$Cellcount * 100

################################################################################
# Count the number of host and donor cells in the ICM for each embryo
################################################################################
g6.icmtype <- g6.chimeras %>% 
  filter(TE_ICM == 'ICM', Channel == 'CH2') %>% 
  group_by(Embryo_ID, Litter, Experiment, 
           Treatment, Embryo_size, TE_ICM, 
           Cellcount, icm.count, 
           H_genotype, D_genotype, 
           t0.donor, cell_type) %>%
  summarise(icm.type = n())
# Account for zeroes - there'll be instances of ICMs 
# with no donor or no host cells, because of chance, as well as
# ICMs in control embryos, which are 100% host, 0% donor
# Cast to wide format
m.g6 <- dcast(g6.icmtype, Embryo_ID + Litter + Experiment + Treatment + 
                Embryo_size + TE_ICM + Cellcount + icm.count + 
                H_genotype + D_genotype + 
                t0.donor ~ cell_type, 
              value.var = 'icm.type')
# Replace NAs with zeros in donor and host columns
m.g6$donor[is.na(m.g6$donor)] <- 0
m.g6$host[is.na(m.g6$host)] <- 0
# Melt table back to long format
g6.icmtype <- melt(m.g6, id.vars = c('Embryo_ID', 'Litter', 'Experiment', 
                                     'Treatment', 'Embryo_size', 
                                     'TE_ICM', 'Cellcount', 
                                     'icm.count', 'H_genotype', 
                                     'D_genotype', 't0.donor'), 
                   variable.name = 'cell_type', value.name = 'icm.type')
rm(m.g6)
# Calculate the percentage of the ICM that each cell type represents
g6.icmtype$pc.icm <- g6.icmtype$icm.type / g6.icmtype$icm.count * 100

################################################################################
# Stratify embryos based on final % of ICM made up of donor cells
# this will be used to group embryos in plots of ICM composition and 
# reduce noise due to the chance of cells ending up in TE and ICM
################################################################################

# Define 20% bins
cutz <- seq(from = 0, to = 100, by = 20)
# Cut donor.icm into 20% bins (donor.icm is the % of ICM made up of donor cells)
donor.icm <- g6.icmtype %>% filter(cell_type == 'donor') %>%
  select(Embryo_ID, pc.icm)
donor.icm$donor.end <- cut(donor.icm$pc.icm, breaks = cutz, 
                           right = F, include.lowest = T)
rm(cutz)
# Combine these strata with main counts table generated above
donor.icm <- donor.icm %>% select(Embryo_ID, donor.end)
g6.icmtype <- merge(g6.icmtype, donor.icm)

# And combine with main table too
g6.chimeras <- merge(g6.chimeras, donor.icm)
rm(donor.icm)

################################################################################
# Count the overall number of cells per lineage
################################################################################
g6.lincounts <- g6.chimeras %>% 
  filter(Channel == 'CH2') %>% 
  group_by(Experiment, Embryo_ID, Treatment,
           Litter, TE_ICM, Cellcount, 
           icm.count, H_genotype, D_genotype, 
           Embryo_size, t0.donor, donor.end, 
           Identity.hc) %>%
  summarise(lin.count = n())
# Account for zeroes, which are not generated by summarize() above
# Split ICM from TE cells
m.g6 <- subset(g6.lincounts, TE_ICM == 'ICM')
t.g6 <- subset(g6.lincounts, TE_ICM != 'ICM')
# Cast ICM cells to wide format
m.g6 <- dcast(m.g6, Experiment + Litter + Embryo_ID + Treatment + Cellcount + 
                TE_ICM + icm.count + H_genotype + D_genotype + 
                Embryo_size + t0.donor + donor.end ~ Identity.hc, 
              value.var = 'lin.count')
# Replace NAs in each ICM lineage denomination with zeros
m.g6[is.na(m.g6)] <- 0
# Melt ICM back to long format
m.g6 <- melt(m.g6, id.vars = c('Experiment', 'Litter', 'Embryo_ID', 
                               'Treatment', 'Cellcount', 'TE_ICM', 
                               'icm.count', 'H_genotype', 'D_genotype', 
                               'Embryo_size', 't0.donor', 'donor.end'), 
             variable.name = 'Identity.hc', value.name = 'lin.count')
# Combine TE and ICM cells again
g6.lincounts <- rbind.fill(m.g6, t.g6)
rm(m.g6, t.g6)
# Calculate the % of ICM that each lineage represents in each embryo
g6.lincounts$pc.icm <- g6.lincounts$lin.count / g6.lincounts$icm.count * 100

################################################################################
# Count the number of GFP+ (donor) and GFP- (host) cells 
# in each lineage in each embryo
################################################################################
g6.lintype <- g6.chimeras %>% 
  filter(Channel == 'CH2') %>% 
  group_by(Embryo_ID, Litter, Experiment, 
           Treatment, Embryo_size, TE_ICM, 
           Cellcount, icm.count, 
           H_genotype, D_genotype, 
           t0.donor, donor.end, 
           Identity.hc, cell_type) %>%
  summarise(lin.type = n())
# Account for zeroes
# Cast to wide format
m.g6 <- dcast(g6.lintype, Embryo_ID + Litter + Experiment + Treatment + 
                Embryo_size + TE_ICM + Cellcount + icm.count + 
                H_genotype + D_genotype + t0.donor + donor.end + 
                Identity.hc ~ cell_type, 
              value.var = 'lin.type')
# Replace NAs with zeros in donor and host columns
m.g6$donor[is.na(m.g6$donor)] <- 0
m.g6$host[is.na(m.g6$host)] <- 0
# Melt ICM back to long format
# Melt table back to long format
g6.lintype <- melt(m.g6, id.vars = c('Embryo_ID', 'Litter', 'Experiment', 
                                     'Treatment', 'Embryo_size', 'TE_ICM', 
                                     'Cellcount', 'icm.count', 
                                     'H_genotype', 'D_genotype', 
                                     't0.donor', 'donor.end', 'Identity.hc'), 
                   variable.name = 'cell_type', value.name = 'lin.type')
rm(m.g6)
# Combine with cell counts per lineage, previously calculated
counts <- g6.lincounts %>% 
  select(Embryo_ID, Identity.hc, lin.count)
g6.lintype <- merge(counts, g6.lintype)
rm(counts)
# Calculate the percentage of the total in each lineage
g6.lintype$pc.lin <- g6.lintype$lin.type/g6.lintype$lin.count * 100 

################################################################################
# Write some tables to file
write.csv(g6.lincounts, file = './data/processed/emb-xim-counts.csv', 
          row.names = F)
write.csv(g6.lintype, file = './data/processed/emb-xim-typecounts.csv', 
          row.names = F)
