# This script takes in the raw output generated by esc-xim_read.R
# and performs transformations on the data, namely:
# * correcting for fluorescence decay along the Z-axis

# Check that setup.R has been ran
setup.ran <- exists('looks')
if (setup.ran == F) { 
  source('./src/setup.R')
}
rm(setup.ran)

# Check if data is already loaded and read it in if not
data.exsts <- exists('esc.chimeras')
if(data.exsts == F) { 
  esc.chimeras <- read.csv('./data/raw/esc-xim-raw.csv')
  esc.ref <- read.csv('./references/esc-xim_exp_ref.csv')
}
rm(data.exsts)

# If there is no raw data, run script to generate it
data.exsts <- exists('esc.chimeras')
if(data.exsts == F) { 
  source('./src/data/esc-xim_read.R')
  esc.ref <- read.csv('./references/esc-xim_exp_ref.csv')
}
rm(data.exsts)

# Load functions that will be used in the script
source('./src/functions/eb_cor.R')

# Load immunofluorescence reference file and merge with main table
esc.if <- read.csv('./references/esc-xim_if.csv')
esc.chimeras <- merge(esc.chimeras, esc.if)

# Order the levels of factors as desired
esc.chimeras$Treatment <- factor(esc.chimeras$Treatment, 
                                 levels = c('Littermate', 'Control', 'Chimera'))
esc.chimeras$TE_ICM <- factor(esc.chimeras$TE_ICM, levels = c('TE', 'ICM'))
# esc.chimeras$Genotype1 <- factor(esc.chimeras$Genotype1, 
#                                  levels = c('wt', 'fl/fl', 'fl/ko', 'ko', 
#                                             'unclear', 'unknown', 'tbd'))

# Rename experiment variable to account for treatments
esc.chimeras$Experiment <- paste(esc.chimeras$Experiment, 
                                 esc.chimeras$Treatment, sep = '.')

# Extract IF information
unicos <- esc.chimeras %>% filter(Channel %in% c('CH2', 'CH3', 'CH5')) %>% 
  group_by(Experiment, Treatment, Genotype1, 
           Genotype2, Channel, Marker) %>% 
  summarize()
unicos <- dcast(unicos, Experiment + Treatment + Genotype1 + Genotype2 ~ 
                  Channel, value.var = 'Marker')

# Extract Channel 2 IF information
ch2.marker <- unicos[, c(1:5)]
ch2.marker <- rename(ch2.marker, 'CH2.marker' = 'CH2')
# and incorporate into main table
esc.chimeras <- merge(esc.chimeras, ch2.marker)
rm(ch2.marker)

################################################################################
# Correct for fluorescence decay along the Z-axis
################################################################################

## Correct for Z-associated fluorescence decay for all channels

# Define the possible channels to go through
channels <- c('CH1.Avg', 'CH2.Avg', 'CH3.Avg', 'CH5.Avg')
# Create an empty matrix to hold the corrected values
# with the length of the number of cells in the dataset
ebLogCor <- matrix(0, nrow = length(esc.chimeras$Embryo_ID), 
                   # and as many columns as channels
                   ncol = length(channels),
                   dimnames = list(c(), channels))
# For each channel in 'channels', perform EB correction 
# and store in the corresponding column in 'ebLogCor'
# Critically, use the secondary antibody as grouping variable for ebcor()
# (see annotation in eb_cor.R for details)
for (c in channels) {
  ebLogCor[, c] <- ebcor(esc.chimeras, c, group = esc.chimeras$CH2.marker)
}

# NOTE: this correction method undercorrects the GFP levels for the donor ESCs
# Uncomment below to visualize the effect:
# qplot(Z, CH2.ebLogCor, data = esc.chimeras, color = Identity) + theme_bw() + 
#         facet_wrap( ~ CH2.ab2)

# This issue could be fixed by further grouping by CH2.ab2 AND Identity
# however, this would cause higher fragmentation in the dataset, which I think
# would make the correction less robust. Moreover, the levels of GFP in 
# donor ESCs are irrelevant, as they have been manually classified.

# Convert ebLogCor to data frame and rename columns to CHX.ebLogCor
ebLogCor <- data.frame(ebLogCor)
ebLogCor <- rename(ebLogCor, CH1.ebLogCor = CH1.Avg, 
                   CH2.ebLogCor = CH2.Avg, 
                   CH3.ebLogCor = CH3.Avg,
                   CH5.ebLogCor = CH5.Avg)

# Combine chimeras with the EB corrected values
esc.chimeras <- cbind(esc.chimeras, ebLogCor)
rm(ebLogCor)

################################################################################
# Write data out to interim folder
write.csv(esc.chimeras, file = './data/interim/esc-xim-tx.csv', 
          row.names = F)

# Calculate the number of embryos per treatment
n.embryos <- esc.chimeras %>% 
  filter(interaction(Channel, Marker) != 'CH2.no.ab', 
         !Litter %in% small.odd) %>% 
  group_by(Embryo_ID, Treatment, 
           ESC_line, ES_culture, 
           ESC_genotype, Stage.t0, 
           Genotype1, D_cells) %>% 
  summarize() %>% 
  group_by(Treatment, ESC_line, ES_culture, ESC_genotype, 
           Stage.t0, Genotype1, D_cells) %>% 
  summarize(N = n())
n.embryos <- dcast(n.embryos, Treatment + Genotype1 + D_cells ~ 
                     Stage.t0 + ESC_line + ESC_genotype + ES_culture, 
                   value.var = 'N')
n.embryos[is.na(n.embryos)] <- '--'
# and write it out as a .csv file
write.csv(n.embryos, file = './results/esc-xim_N-embryos.csv', row.names = F)

