# This script counts cells of each type in the ESC chimeras dataset
# generated by esc-xim_classify.R
# Note I am using the ICM cell identity determined by Hierarchical clustering

# Check if setup.R has been ran
setup.ran <- exists('looks')
if (setup.ran == F) { 
  source('./src/setup.R')
}
rm(setup.ran)

# Check if data is already loaded and read it in if not
data.exsts <- exists('esc.chimeras')
if(data.exsts == F) { 
  esc.chimeras <- read.csv('./data/processed/esc-xim-processed.csv')
  esc.ref <- read.csv('./references/esc-xim_exp_ref.csv')
}
rm(data.exsts)

# If there is no raw data, run script to generate it
data.exsts <- exists('esc.chimeras')
if(data.exsts == F) { 
  source('./src/data/esc-xim_classify.R')
  esc.ref <- read.csv('./references/esc-xim_exp_ref.csv')
}
rm(data.exsts)

################################################################################
# Calculate number of embryos per experimental group
# and write it out to disk
################################################################################

# If esc-xim_read.R has not been ran before and data is loaded
# directly from ./data/interim/, generate vector of embryos to 
# exclude from analysis (see ./src/data/esc-xim_read.R for details)
if(exists('small.odd') == F) { 
  small.odd <- unique(subset(esc.chimeras, 
                             Exp_date >= 20180214 & 
                               Exp_date <= 20180222)$Litter)
}

# Calculate the number of embryos per treatment
n.embryos <- esc.chimeras %>% 
  filter(interaction(Channel, Marker) != 'CH2.no.ab', 
         !Litter %in% small.odd) %>% 
  group_by(Embryo_ID, Treatment, 
           ESC_line, ES_culture, 
           ESC_genotype, Stage.t0, 
           Genotype1, D_cells) %>% 
  summarize() %>% 
  group_by(Treatment, ESC_line, ES_culture, ESC_genotype, 
           Stage.t0, Genotype1, D_cells) %>% 
  summarize(N = n())
n.embryos <- dcast(n.embryos, Treatment + Genotype1 + D_cells ~ 
                     Stage.t0 + ESC_line + ESC_genotype + ES_culture, 
                   value.var = 'N')
n.embryos[is.na(n.embryos)] <- '--'
# and write it out as a .csv file
write.csv(n.embryos, file = './results/esc-xim_N-embryos.csv', row.names = F)

################################################################################
# Calculate the number of cells per lineage for each embryo
################################################################################

esc.xim.lincounts <- esc.chimeras %>% 
  group_by(Experiment, Litter, Exp_date, Img_date, 
           Embryo_ID, TE_ICM, Cellcount, Stage, 
           Gene1, Genotype1, Gene2, Genotype2, 
           Background, Treatment, ESC_line, ES_culture, 
           ESC_genotype, H_cells, D_cells, ESC_t0, Cre, 
           Culture_time, Stage.t0, Identity.hc, icm.count, 
           group.median) %>%
  summarize(count = n())
# Account for zeroes like in mutants or anywhere where a cell type is missing
# Split ICM from TE cells
m.xim <- subset(esc.xim.lincounts, TE_ICM == 'ICM')
t.xim <- subset(esc.xim.lincounts, TE_ICM != 'ICM')
# Cast ICM cells to wide format
m.xim <- dcast(m.xim, Experiment + Exp_date + Img_date + Litter + Embryo_ID + 
                 Cellcount + TE_ICM + Stage + Treatment + Background + 
                 icm.count + group.median + Genotype1 + Gene1 + 
                 Genotype2 + Gene2 + ESC_line + ESC_genotype + 
                 ES_culture + ESC_t0 + H_cells + D_cells + Culture_time + 
                 Cre + icm.count + group.median + Stage.t0 ~ 
                 Identity.hc, value.var = 'count')
# Replace NAs in each ICM lineage denomination with zeros
m.xim[is.na(m.xim)] <- 0
# Melt ICM back to long format
m.xim <- melt(m.xim, id.vars = c('Experiment', 'Litter', 
                                 'Exp_date', 'Img_date', 'Embryo_ID', 'TE_ICM', 
                                 'Cellcount', 'Stage', 'Background', 
                                 'Treatment', 'Gene1', 'Genotype1', 
                                 'Gene2', 'Genotype2', 'ESC_line', 
                                 'ESC_genotype', 'ESC_t0', 'ES_culture', 
                                 'H_cells', 'D_cells', 
                                 'Culture_time', 'Stage.t0', 'Cre', 
                                 'icm.count', 'group.median'), 
              variable.name = 'Identity.hc', value.name = 'count')
# Combine TE and ICM cells again
esc.xim.lincounts <- rbind.fill(m.xim, t.xim)
rm(m.xim, t.xim)
# Calculate the percentage of the ICM each lineage represents
esc.xim.lincounts$pc.icm <- esc.xim.lincounts$count / 
  esc.xim.lincounts$icm.count * 100

# Make and order factors
esc.xim.lincounts$ES_culture <- factor(esc.xim.lincounts$ES_culture, 
                                       levels = c('S/LIF', '2i/LIF', 'no.esc'))
esc.xim.lincounts$Genotype1 <- factor(esc.xim.lincounts$Genotype1, 
                                      levels = c('wt', 'fl/fl',
                                                 'fl/ko', 'ko', 
                                                 'mosaic', 'unknown', 
                                                 'tbd'))
esc.xim.lincounts$ESC_genotype <- factor(esc.xim.lincounts$ESC_genotype, 
                                         levels = c('wt', 'het', 'ko', 'no.esc'))

################################################################################
## Calculate the number of host ICM cells for each embryo
################################################################################
hostcells <- esc.xim.lincounts %>% 
  filter(TE_ICM == 'ICM' & Identity.hc != 'ESC') %>% 
  group_by(Embryo_ID, Identity.hc, count) %>% 
  summarize() %>% 
  group_by(Embryo_ID) %>% summarize(host.icm = sum(count))
esc.xim.lincounts <- merge(esc.xim.lincounts, hostcells)
rm(hostcells)

################################################################################
# Make wide format table with number of PrE, EPI and ESC as variabls
################################################################################
esc.xim.lincounts2 <- esc.xim.lincounts %>% 
  filter(Identity.hc %in% c('PRE', 'ESC', 'EPI')) %>% 
  group_by(Exp_date, Embryo_ID, Litter, Genotype1, Stage.t0, 
           ESC_line, ESC_genotype, ES_culture, D_cells, 
           Treatment, icm.count, Identity.hc, count) %>% 
  summarize() 
esc.xim.lincounts2 <- dcast(esc.xim.lincounts2, Exp_date + 
                              Embryo_ID + Litter + Genotype1 + Stage.t0 + 
                              Treatment + ES_culture + 
                              ESC_line + ESC_genotype + 
                              icm.count + D_cells ~ Identity.hc, 
                            value.var = 'count')

# Group embryos that received 8-12 ESCs in one category
esc.xim.lincounts2$D_cells[which(
  esc.xim.lincounts2$D_cells %in% c(8, 10, 12))] <- '8-12'
esc.xim.lincounts2$D_cells <- factor(esc.xim.lincounts2$D_cells, 
                                     levels = c('0', '1', '2', '3', 
                                                '4', '5', '8-12'))

# Assign categories based on bins of the final number of ESCs
# Split Controls and Littermates from Chimeras
aa <- subset(esc.xim.lincounts2, Treatment != 'Chimera' |
               ESC == 0)
bb <- subset(esc.xim.lincounts2, ESC > 0)
# Zero ESCs in Control and Littermates
aa$esc.end <- 0
# Bin #ESCx in chimeras
cutz <- c(0, 1, 5, 10, 20, 40, 80)
binz <- c('0', '0.5x', '1x', '2x', '4x', '8x')
bb$esc.end <- cut(bb$ESC, breaks = cutz, 
                  labels = binz, right = F)
# Combine data together again
esc.xim.lincounts2 <- rbind(aa, bb)
esc.xim.lincounts2$esc.end <- factor(esc.xim.lincounts2$esc.end, 
                                     levels = c(binz))

esc.end <- select(esc.xim.lincounts2, Embryo_ID, esc.end)
esc.xim.lincounts <- merge(esc.xim.lincounts, esc.end)
rm(cutz, binz, aa, bb)

################################################################################
# Write counts out to file
write.csv(esc.xim.lincounts, file = './data/processed/esc-xim-counts.csv', 
          row.names = F)
write.csv(esc.xim.lincounts2, file = './data/processed/esc-xim-widecounts.csv', 
          row.names = F)


