# This script counts cells of each type in the new-littermates dataset
# generated by new-lms_tx.R and new-lms_classify.R.
# Note I am using the ICM cell identity determined by Hierarchical clustering

# Check if setup.R has been ran
setup.ran <- exists('looks')
if (setup.ran == F) { 
  source('./src/setup.R')
}
rm(setup.ran)

# Check if data is already loaded 
data.exsts <- exists('new.lms')
if(data.exsts == F) { 
  new.lms <- read.csv('./data/processed/new-lms-processed.csv')
  new.lms.ref <- rbind(read.csv('./references/new-littermates_exp_ref.csv'), 
                       read.csv('./references/fgf4-lms_exp_ref.csv'))
}
rm(data.exsts)

# If there is no processed data frame, run script to generate it
data.exsts <- exists('new.lms')
if(data.exsts == F) { 
  source('./src/data/new-lms_classify.R')
  new.lms.ref <- rbind(read.csv('./references/new-littermates_exp_ref.csv'), 
                       read.csv('./references/fgf4-lms_exp_ref.csv'))
}
rm(data.exsts)

################################################################################
# Count number of cells per lineage using the Identity varible
# which corresponds to Identity.hc for most embryos, 
# and to Identity.km for Fgf4 subset (see new-lms_classify.R)
################################################################################

# Calculate cell counts using new Identity variable
new.lms.counts <- new.lms %>% filter(Channel == 'CH2') %>% 
  group_by(Exp_date, Img_date, Experiment, 
           Litter, Embryo_ID, Treatment, 
           Gene1, Gene2, Genotype1, Genotype2, 
           Cellcount, Stage, TE_ICM, 
           litter.median, Identity, 
           icm.count, Background) %>% 
  summarize(count = n())

# In embryos that lack a certain cell type, that isn't registered as a 0
# by default summarizing the data in the step above

# Split ICM from TE cells
m.new <- subset(new.lms.counts, TE_ICM == 'ICM')
t.new <- subset(new.lms.counts, TE_ICM != 'ICM')

# Cast ICM cells to wide format so that each ICM denomination
# becomes a variable (PRE, DP, etc)
m.new <- dcast(m.new, Exp_date + Img_date + Experiment + Litter + Embryo_ID + 
                 Cellcount + TE_ICM + Stage + Treatment + Background + 
                 icm.count + litter.median + Genotype1 + Gene1 + 
                 Genotype2 + Gene2 ~ Identity, value.var = 'count')
# Replace the resulting NAs in each ICM lineage denomination with zeros
m.new[is.na(m.new)] <- 0

# Melt ICM back to long format where all cell types are under Identity
m.new <- melt(m.new, id.vars = c('Exp_date', 'Img_date', 'Experiment', 'Litter', 
                                 'Embryo_ID', 'Cellcount', 'TE_ICM', 
                                 'Treatment', 'Stage', 'Background', 
                                 'Gene1', 'Genotype1', 'Gene2', 'Genotype2', 
                                 'icm.count', 'litter.median'), 
              variable.name = 'Identity', value.name = 'count')

# Combine TE and ICM cells again
new.lms.counts <- rbind.fill(m.new, t.new)
rm(m.new, t.new)

# Calculate the % of the ICM that each lineage represents
new.lms.counts$pc.icm <- new.lms.counts$count / 
  new.lms.counts$icm.count * 100

################################################################################
# Write out data to the ./data/processed folder
write.csv(new.lms.counts, file = './data/processed/new-lms-counts.csv', 
          row.names = F)

##